### ISSUE TITLE
no method to return a node's weight relative to it's parent

### ISSUE THREAD

**Issue by davidjmemmett** [creaven/miftree#2]
There is currently no way to return the weight of a node relative to it's parent. The method getVisiblePosition returns the weight relative to the root. I have written a small plugin and am new to using git, do I create my own branch, or just send along a patch?

**Comment by davidjmemmett** [comment]
I created a Gist, seemed appropriate.
http://gist.github.com/348171

**Comment by creaven** [comment]
weight? what is it? node position/index? You should use standart indexOf array method: node.getParent().getChildren().indexOf(node);

**Comment by davidjmemmett** [comment]
I feel like a tit! Many apologies, I should've seriously known better! Can you delete bugs on here?

**Comment by creaven** [comment]
issue just closed.
