### ISSUE TITLE
Duplication of items in tree

### ISSUE THREAD

**Issue by davidjmemmett** [creaven/miftree#3]
I cannot reproduce this, however sometimes when using Mif.Tree.Drag and dragging a node around the tree, the node will duplicate (remain in it's original place and create a new identical node wherever you drop the node. It's really annoying, occurs randomly in a variety of browsers (Chromium on CentOS/Firefox on OS X Leopard). I wish I could reproduce this, but I'm hoping someone else might have managed to and can provide some additional information for you.

**Comment by creaven** [comment]
node will be copied if you press control

**Comment by davidjmemmett** [comment]
Doesn't do it for me :/

**Comment by davidjmemmett** [comment]
Just found that Ctrl+Shift duplicates. I can confirm that this happens randomly without any keys held down. How do I disable this functionality?

**Comment by davidjmemmett** [comment]
Setting "modifier" property on Mif.Tree.Drag to a blank value disables this. In all honesty, it is Ctrl+Shift and not just Ctrl.

**Comment by creaven** [comment]
it's control.

**Comment by davidjmemmett** [comment]
I will guarantee you that it isn't for me. Whilst the code states that the default is "control", the actual keys required are both Ctrl and Shift. Have you tested this? If so, what browser, platform etc?

**Comment by creaven** [comment]
sure it's tested. mac os x 10.5/windows xp ff/safari/ie. It's just check event.control, event.control always true if ctrl pressed

**Comment by davidjmemmett** [comment]
It's not working for me with just control pressed. Not sure why this bug is closed.

Forgot to mention, great library, thanks for trying. ;)
