### ISSUE TITLE
Duplicating of nodes on drag and drop

### ISSUE THREAD

**Issue by nyankovskiy** [creaven/miftree#6]
Short description:

When drag and drop existing node on the collapsed loadable node it sometimes appears two same nodes after loadable node is loaded.

Expected behavior:

It should be only one node in the loadable node after drag and drop and expanding.

Steps to reproduce:
1. Create a tree with several nodes and several tree levels. It should be a collapsed loadable node, that will get it's structure via ajax request on expand.
2. In Drag and Drop event add a method, that will send an ajax request to save new position of the node.
3. When the node is collapsed drag another node on it.
4. Sometimes it happens, that after node is expanded - the node that was moved in it is duplicated.

Some investigations:

It happens when the loading of node is not finished but the save request is finished. So in child tree data there is already moved node. And after that node is moved in the GUI. That causes duplicationg.

**Comment by creaven** [comment]
not a Mif.Tree issue, save request can be send after move.

**Comment by nyankovskiy** [comment]
It's sent after moving, but there is another request that is loading data for collapsed node.

So
1. we move
2. we send request
3. we load data for expanding row
4. we get duplicates.

In that case, how can i get a node status whether it's already loaded or not? Just to finish darg and drop operation right after the collapsed node is expanded?

**Comment by creaven** [comment]
drag->drop on collapsed not loaded node->loading->move. Move always happens after loading and expanding.
Send request after move.
event - move, tree.addEvent('move', ...)
